@PatientManagementSystemAPI_HostAddress = https://localhost:7104

POST {{PatientManagementSystemAPI_HostAddress}}/api/appointment
Content-Type: application/json

{
  //Appointment
}

###

@id=13
DELETE {{PatientManagementSystemAPI_HostAddress}}/api/appointment/{{id}}

###

PUT {{PatientManagementSystemAPI_HostAddress}}/api/appointment/{{id}}
Content-Type: application/json

{
  //Appointment
}

###

POST {{PatientManagementSystemAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  Dummy2
}

###

POST {{PatientManagementSystemAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email":"pradeep@c9.com",
  "password":"Pradeep12"
}

###

@doctorId=2
GET {{PatientManagementSystemAPI_HostAddress}}/api/appointment/doctor/{{doctorId}}

###

GET {{PatientManagementSystemAPI_HostAddress}}/api/appointment/doctor/{{doctorId}}

###

GET {{PatientManagementSystemAPI_HostAddress}}/api/patient/getAllPatients

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/appointment/{{id}}

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/Users/{{id}}

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/Users

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/Users

###

@userId=13
DELETE {{PatientManagementSystemAPI_HostAddress}}/api/users/{id}?userId={{userId}}

###
