@PatientManagementSystemAPI_HostAddress = https://localhost:7104

POST {{PatientManagementSystemAPI_HostAddress}}/api/appointment
Content-Type: application/json

{
  //Appointment
}

###

@id=13
DELETE {{PatientManagementSystemAPI_HostAddress}}/api/appointment/{{id}}

###

PUT {{PatientManagementSystemAPI_HostAddress}}/api/appointment/{{id}}
Content-Type: application/json

{
  //Appointment
}

###

POST {{PatientManagementSystemAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  Dummy2
}

###

POST {{PatientManagementSystemAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email":"pradeep@c9.com",
  "password":"Pradeep12"
}

###

@doctorId=2
GET {{PatientManagementSystemAPI_HostAddress}}/api/appointment/doctor/{{doctorId}}

###

GET {{PatientManagementSystemAPI_HostAddress}}/api/appointment/doctor/{{doctorId}}

###

GET {{PatientManagementSystemAPI_HostAddress}}/api/patient/getAllPatients

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/appointment/delete/32

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/Users/{{id}}

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/Users

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/Users

###

@userId=13
DELETE {{PatientManagementSystemAPI_HostAddress}}/api/users/{id}?userId={{userId}}

###

GET {{PatientManagementSystemAPI_HostAddress}}/api/profile/{{userId}}

###

POST {{PatientManagementSystemAPI_HostAddress}}/api/profile
Content-Type: application/json

{
  "applicationUserId": 1,
 
  "dateOfBirth": "1990-01-01T00:00:00",
  "gender": "Male",
  "phoneNumber": "1234567890",
  "bio": "Passionate about health and wellness.",
  "address": "123 Main Street, Suite 200",
  "city": "Hyderabad",
  "cityState": "Telangana",
  "country": "India",
  "firstName":"Aditya Malluvalasa",
  "email":"adithya@c9.com"
}

###
@userId=1
GET {{PatientManagementSystemAPI_HostAddress}}/api/profile/{{userId}}

###
@id=1
PUT {{PatientManagementSystemAPI_HostAddress}}/api/patient/me
Content-Type: application/json

{
  
  "applicationUserId": 18,

  "dateOfBirth": "2000-01-01T00:00:00"

  
}
###

PUT {{PatientManagementSystemAPI_HostAddress}}/api/patient/{{id}}
Content-Type: application/json

{
  "id": 1,
  "applicationUserId": 1,

  "dateOfBirth": "1998-01-01T00:00:00",

  "firstName": "Aditya Malluvalasa",
  "email": "adithya@c9.com"
}

###


PUT {{PatientManagementSystemAPI_HostAddress}}/api/profile/me
Content-Type: application/json


{

  "applicationUserId": 18,

  "dateOfBirth": "2003-01-01T00:00:00"

}

###

GET {{PatientManagementSystemAPI_HostAddress}}/api/profile/me/46

###

PUT {{PatientManagementSystemAPI_HostAddress}}/api/profile/me/update
Content-Type: application/json

{

  "applicationUserId": 45,
"firstName":"Pranav",
"lastName":"thoutam"

}

###

GET {{PatientManagementSystemAPI_HostAddress}}/api/profile/me/{{userId}}

###

DELETE {{PatientManagementSystemAPI_HostAddress}}/api/profile/me/{{userId}}

###

POST {{PatientManagementSystemAPI_HostAddress}}/api/appointment
Content-Type: application/json

{
  //AppointmentDto
}

###

@patientId=0
GET {{PatientManagementSystemAPI_HostAddress}}/api/vital/getVitals/{{patientId}}

###

POST {{PatientManagementSystemAPI_HostAddress}}/api/vital/addVitals
Content-Type: application/json

{
  //VitalDto
}

###

POST {{PatientManagementSystemAPI_HostAddress}}/api/appointment
Content-Type: application/json

{"doctorId":1052,"patientId":27,"appointmentStartTime":"2025-07-27T01:00:00+05:30","appointmentEndTime":"2025-07-27T01:30:00+05:30","createdBy":"1048"}

###
